use_frameworks!

platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'TTToolKit_Example' do
  pod 'TTToolKit', :path => '../'
  

  target 'TTToolKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
  pod 'Masonry', '~> 1.1.0'
  pod 'LKDBHelper'
  pod 'MBProgressHUD'
#  pod 'TTToolKit', '~> 0.2.1'
end
